/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RenewRouteImport } from './routes/renew'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImpersonateRouteImport } from './routes/impersonate'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ITokenRouteImport } from './routes/i.$token'
import { Route as AppUsageRouteImport } from './routes/app.usage'
import { Route as AppUnitsRouteImport } from './routes/app.units'
import { Route as AppSuppliersRouteImport } from './routes/app.suppliers'
import { Route as AppSubscriptionRouteImport } from './routes/app.subscription'
import { Route as AppStockRouteImport } from './routes/app.stock'
import { Route as AppShiftsRouteImport } from './routes/app.shifts'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppPayInvoiceRouteImport } from './routes/app.pay-invoice'
import { Route as AppInstallmentsRouteImport } from './routes/app.installments'
import { Route as AppCustomersRouteImport } from './routes/app.customers'
import { Route as AppChangePasswordRouteImport } from './routes/app.change-password'
import { Route as AppCategoriesRouteImport } from './routes/app.categories'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSmsLogsRouteImport } from './routes/admin.sms-logs'
import { Route as AdminShopsRouteImport } from './routes/admin.shops'
import { Route as AdminSetupRouteImport } from './routes/admin.setup'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPackagesRouteImport } from './routes/admin.packages'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminImpersonationLogsRouteImport } from './routes/admin.impersonation-logs'
import { Route as AdminDemoRequestsRouteImport } from './routes/admin.demo-requests'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as AppSalesIndexRouteImport } from './routes/app.sales.index'
import { Route as AppReportsIndexRouteImport } from './routes/app.reports.index'
import { Route as AppPurchasesIndexRouteImport } from './routes/app.purchases.index'
import { Route as AppProductsIndexRouteImport } from './routes/app.products.index'
import { Route as AppCustomersIndexRouteImport } from './routes/app.customers.index'
import { Route as AdminShopsIndexRouteImport } from './routes/admin.shops.index'
import { Route as AppSettingsInvoiceTemplateRouteImport } from './routes/app.settings.invoice-template'
import { Route as AppSalesNewRouteImport } from './routes/app.sales.new'
import { Route as AppSalesSaleIdRouteImport } from './routes/app.sales.$saleId'
import { Route as AppReportsTaxRouteImport } from './routes/app.reports.tax'
import { Route as AppReportsSupplierPurchaseRouteImport } from './routes/app.reports.supplier-purchase'
import { Route as AppReportsStockMovementRouteImport } from './routes/app.reports.stock-movement'
import { Route as AppReportsStockRouteImport } from './routes/app.reports.stock'
import { Route as AppReportsShiftRouteImport } from './routes/app.reports.shift'
import { Route as AppReportsSalesReturnRouteImport } from './routes/app.reports.sales-return'
import { Route as AppReportsSalesRouteImport } from './routes/app.reports.sales'
import { Route as AppReportsReceivableRouteImport } from './routes/app.reports.receivable'
import { Route as AppReportsPurchaseRouteImport } from './routes/app.reports.purchase'
import { Route as AppReportsProfitRouteImport } from './routes/app.reports.profit'
import { Route as AppReportsProductSalesRouteImport } from './routes/app.reports.product-sales'
import { Route as AppReportsPaymentMethodRouteImport } from './routes/app.reports.payment-method'
import { Route as AppReportsPayableRouteImport } from './routes/app.reports.payable'
import { Route as AppReportsLowStockRouteImport } from './routes/app.reports.low-stock'
import { Route as AppReportsInstallmentRouteImport } from './routes/app.reports.installment'
import { Route as AppReportsDiscountRouteImport } from './routes/app.reports.discount'
import { Route as AppReportsCustomerSalesRouteImport } from './routes/app.reports.customer-sales'
import { Route as AppReportsCategorySalesRouteImport } from './routes/app.reports.category-sales'
import { Route as AppReportsCashBookRouteImport } from './routes/app.reports.cash-book'
import { Route as AppReportsBkashBookRouteImport } from './routes/app.reports.bkash-book'
import { Route as AppPurchasesNewRouteImport } from './routes/app.purchases.new'
import { Route as AppProductsProductIdRouteImport } from './routes/app.products.$productId'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/app.customers.$customerId'
import { Route as AdminShopsShopIdRouteImport } from './routes/admin.shops.$shopId'
import { Route as AdminReceiptsPaymentIdRouteImport } from './routes/admin.receipts.$paymentId'
import { Route as ApiPublicCronInvoiceRemindersRouteImport } from './routes/api/public/cron/invoice-reminders'
import { Route as ApiPublicCronExpiryCheckRouteImport } from './routes/api/public/cron/expiry-check'
import { Route as ApiPublicBkashWebhookRouteImport } from './routes/api/public/bkash/webhook'
import { Route as ApiPublicBkashCallbackRouteImport } from './routes/api/public/bkash/callback'
import { Route as AdminReceiptsEnPaymentIdRouteImport } from './routes/admin.receipts.en.$paymentId'
import { Route as AdminInvoicesEnSubscriptionIdRouteImport } from './routes/admin.invoices.en.$subscriptionId'

const RenewRoute = RenewRouteImport.update({
  id: '/renew',
  path: '/renew',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpersonateRoute = ImpersonateRouteImport.update({
  id: '/impersonate',
  path: '/impersonate',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ITokenRoute = ITokenRouteImport.update({
  id: '/i/$token',
  path: '/i/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppUnitsRoute = AppUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppShiftsRoute = AppShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPayInvoiceRoute = AppPayInvoiceRouteImport.update({
  id: '/pay-invoice',
  path: '/pay-invoice',
  getParentRoute: () => AppRoute,
} as any)
const AppInstallmentsRoute = AppInstallmentsRouteImport.update({
  id: '/installments',
  path: '/installments',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppChangePasswordRoute = AppChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSmsLogsRoute = AdminSmsLogsRouteImport.update({
  id: '/sms-logs',
  path: '/sms-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShopsRoute = AdminShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImpersonationLogsRoute = AdminImpersonationLogsRouteImport.update({
  id: '/impersonation-logs',
  path: '/impersonation-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDemoRequestsRoute = AdminDemoRequestsRouteImport.update({
  id: '/demo-requests',
  path: '/demo-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppPurchasesIndexRoute = AppPurchasesIndexRouteImport.update({
  id: '/purchases/',
  path: '/purchases/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCustomersRoute,
} as any)
const AdminShopsIndexRoute = AdminShopsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminShopsRoute,
} as any)
const AppSettingsInvoiceTemplateRoute =
  AppSettingsInvoiceTemplateRouteImport.update({
    id: '/settings/invoice-template',
    path: '/settings/invoice-template',
    getParentRoute: () => AppRoute,
  } as any)
const AppSalesNewRoute = AppSalesNewRouteImport.update({
  id: '/sales/new',
  path: '/sales/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesSaleIdRoute = AppSalesSaleIdRouteImport.update({
  id: '/sales/$saleId',
  path: '/sales/$saleId',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsTaxRoute = AppReportsTaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsSupplierPurchaseRoute =
  AppReportsSupplierPurchaseRouteImport.update({
    id: '/supplier-purchase',
    path: '/supplier-purchase',
    getParentRoute: () => AppReportsRoute,
  } as any)
const AppReportsStockMovementRoute = AppReportsStockMovementRouteImport.update({
  id: '/stock-movement',
  path: '/stock-movement',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsStockRoute = AppReportsStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsShiftRoute = AppReportsShiftRouteImport.update({
  id: '/shift',
  path: '/shift',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsSalesReturnRoute = AppReportsSalesReturnRouteImport.update({
  id: '/sales-return',
  path: '/sales-return',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsSalesRoute = AppReportsSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsReceivableRoute = AppReportsReceivableRouteImport.update({
  id: '/receivable',
  path: '/receivable',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsPurchaseRoute = AppReportsPurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsProfitRoute = AppReportsProfitRouteImport.update({
  id: '/profit',
  path: '/profit',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsProductSalesRoute = AppReportsProductSalesRouteImport.update({
  id: '/product-sales',
  path: '/product-sales',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsPaymentMethodRoute = AppReportsPaymentMethodRouteImport.update({
  id: '/payment-method',
  path: '/payment-method',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsPayableRoute = AppReportsPayableRouteImport.update({
  id: '/payable',
  path: '/payable',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsLowStockRoute = AppReportsLowStockRouteImport.update({
  id: '/low-stock',
  path: '/low-stock',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsInstallmentRoute = AppReportsInstallmentRouteImport.update({
  id: '/installment',
  path: '/installment',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsDiscountRoute = AppReportsDiscountRouteImport.update({
  id: '/discount',
  path: '/discount',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsCustomerSalesRoute = AppReportsCustomerSalesRouteImport.update({
  id: '/customer-sales',
  path: '/customer-sales',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsCategorySalesRoute = AppReportsCategorySalesRouteImport.update({
  id: '/category-sales',
  path: '/category-sales',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsCashBookRoute = AppReportsCashBookRouteImport.update({
  id: '/cash-book',
  path: '/cash-book',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsBkashBookRoute = AppReportsBkashBookRouteImport.update({
  id: '/bkash-book',
  path: '/bkash-book',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppPurchasesNewRoute = AppPurchasesNewRouteImport.update({
  id: '/purchases/new',
  path: '/purchases/new',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsProductIdRoute = AppProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => AppCustomersRoute,
} as any)
const AdminShopsShopIdRoute = AdminShopsShopIdRouteImport.update({
  id: '/$shopId',
  path: '/$shopId',
  getParentRoute: () => AdminShopsRoute,
} as any)
const AdminReceiptsPaymentIdRoute = AdminReceiptsPaymentIdRouteImport.update({
  id: '/receipts/$paymentId',
  path: '/receipts/$paymentId',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicCronInvoiceRemindersRoute =
  ApiPublicCronInvoiceRemindersRouteImport.update({
    id: '/api/public/cron/invoice-reminders',
    path: '/api/public/cron/invoice-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronExpiryCheckRoute =
  ApiPublicCronExpiryCheckRouteImport.update({
    id: '/api/public/cron/expiry-check',
    path: '/api/public/cron/expiry-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBkashWebhookRoute = ApiPublicBkashWebhookRouteImport.update({
  id: '/api/public/bkash/webhook',
  path: '/api/public/bkash/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBkashCallbackRoute = ApiPublicBkashCallbackRouteImport.update({
  id: '/api/public/bkash/callback',
  path: '/api/public/bkash/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReceiptsEnPaymentIdRoute =
  AdminReceiptsEnPaymentIdRouteImport.update({
    id: '/receipts/en/$paymentId',
    path: '/receipts/en/$paymentId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminInvoicesEnSubscriptionIdRoute =
  AdminInvoicesEnSubscriptionIdRouteImport.update({
    id: '/invoices/en/$subscriptionId',
    path: '/invoices/en/$subscriptionId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/impersonate': typeof ImpersonateRoute
  '/login': typeof LoginRoute
  '/renew': typeof RenewRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/demo-requests': typeof AdminDemoRequestsRoute
  '/admin/impersonation-logs': typeof AdminImpersonationLogsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/shops': typeof AdminShopsRouteWithChildren
  '/admin/sms-logs': typeof AdminSmsLogsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/change-password': typeof AppChangePasswordRoute
  '/app/customers': typeof AppCustomersRouteWithChildren
  '/app/installments': typeof AppInstallmentsRoute
  '/app/pay-invoice': typeof AppPayInvoiceRoute
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/shifts': typeof AppShiftsRoute
  '/app/stock': typeof AppStockRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/units': typeof AppUnitsRoute
  '/app/usage': typeof AppUsageRoute
  '/i/$token': typeof ITokenRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/receipts/$paymentId': typeof AdminReceiptsPaymentIdRoute
  '/admin/shops/$shopId': typeof AdminShopsShopIdRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/products/$productId': typeof AppProductsProductIdRoute
  '/app/purchases/new': typeof AppPurchasesNewRoute
  '/app/reports/bkash-book': typeof AppReportsBkashBookRoute
  '/app/reports/cash-book': typeof AppReportsCashBookRoute
  '/app/reports/category-sales': typeof AppReportsCategorySalesRoute
  '/app/reports/customer-sales': typeof AppReportsCustomerSalesRoute
  '/app/reports/discount': typeof AppReportsDiscountRoute
  '/app/reports/installment': typeof AppReportsInstallmentRoute
  '/app/reports/low-stock': typeof AppReportsLowStockRoute
  '/app/reports/payable': typeof AppReportsPayableRoute
  '/app/reports/payment-method': typeof AppReportsPaymentMethodRoute
  '/app/reports/product-sales': typeof AppReportsProductSalesRoute
  '/app/reports/profit': typeof AppReportsProfitRoute
  '/app/reports/purchase': typeof AppReportsPurchaseRoute
  '/app/reports/receivable': typeof AppReportsReceivableRoute
  '/app/reports/sales': typeof AppReportsSalesRoute
  '/app/reports/sales-return': typeof AppReportsSalesReturnRoute
  '/app/reports/shift': typeof AppReportsShiftRoute
  '/app/reports/stock': typeof AppReportsStockRoute
  '/app/reports/stock-movement': typeof AppReportsStockMovementRoute
  '/app/reports/supplier-purchase': typeof AppReportsSupplierPurchaseRoute
  '/app/reports/tax': typeof AppReportsTaxRoute
  '/app/sales/$saleId': typeof AppSalesSaleIdRoute
  '/app/sales/new': typeof AppSalesNewRoute
  '/app/settings/invoice-template': typeof AppSettingsInvoiceTemplateRoute
  '/admin/shops/': typeof AdminShopsIndexRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/products/': typeof AppProductsIndexRoute
  '/app/purchases/': typeof AppPurchasesIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/app/sales/': typeof AppSalesIndexRoute
  '/admin/invoices/en/$subscriptionId': typeof AdminInvoicesEnSubscriptionIdRoute
  '/admin/receipts/en/$paymentId': typeof AdminReceiptsEnPaymentIdRoute
  '/api/public/bkash/callback': typeof ApiPublicBkashCallbackRoute
  '/api/public/bkash/webhook': typeof ApiPublicBkashWebhookRoute
  '/api/public/cron/expiry-check': typeof ApiPublicCronExpiryCheckRoute
  '/api/public/cron/invoice-reminders': typeof ApiPublicCronInvoiceRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/impersonate': typeof ImpersonateRoute
  '/login': typeof LoginRoute
  '/renew': typeof RenewRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/demo-requests': typeof AdminDemoRequestsRoute
  '/admin/impersonation-logs': typeof AdminImpersonationLogsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/sms-logs': typeof AdminSmsLogsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/change-password': typeof AppChangePasswordRoute
  '/app/installments': typeof AppInstallmentsRoute
  '/app/pay-invoice': typeof AppPayInvoiceRoute
  '/app/shifts': typeof AppShiftsRoute
  '/app/stock': typeof AppStockRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/units': typeof AppUnitsRoute
  '/app/usage': typeof AppUsageRoute
  '/i/$token': typeof ITokenRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/receipts/$paymentId': typeof AdminReceiptsPaymentIdRoute
  '/admin/shops/$shopId': typeof AdminShopsShopIdRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/products/$productId': typeof AppProductsProductIdRoute
  '/app/purchases/new': typeof AppPurchasesNewRoute
  '/app/reports/bkash-book': typeof AppReportsBkashBookRoute
  '/app/reports/cash-book': typeof AppReportsCashBookRoute
  '/app/reports/category-sales': typeof AppReportsCategorySalesRoute
  '/app/reports/customer-sales': typeof AppReportsCustomerSalesRoute
  '/app/reports/discount': typeof AppReportsDiscountRoute
  '/app/reports/installment': typeof AppReportsInstallmentRoute
  '/app/reports/low-stock': typeof AppReportsLowStockRoute
  '/app/reports/payable': typeof AppReportsPayableRoute
  '/app/reports/payment-method': typeof AppReportsPaymentMethodRoute
  '/app/reports/product-sales': typeof AppReportsProductSalesRoute
  '/app/reports/profit': typeof AppReportsProfitRoute
  '/app/reports/purchase': typeof AppReportsPurchaseRoute
  '/app/reports/receivable': typeof AppReportsReceivableRoute
  '/app/reports/sales': typeof AppReportsSalesRoute
  '/app/reports/sales-return': typeof AppReportsSalesReturnRoute
  '/app/reports/shift': typeof AppReportsShiftRoute
  '/app/reports/stock': typeof AppReportsStockRoute
  '/app/reports/stock-movement': typeof AppReportsStockMovementRoute
  '/app/reports/supplier-purchase': typeof AppReportsSupplierPurchaseRoute
  '/app/reports/tax': typeof AppReportsTaxRoute
  '/app/sales/$saleId': typeof AppSalesSaleIdRoute
  '/app/sales/new': typeof AppSalesNewRoute
  '/app/settings/invoice-template': typeof AppSettingsInvoiceTemplateRoute
  '/admin/shops': typeof AdminShopsIndexRoute
  '/app/customers': typeof AppCustomersIndexRoute
  '/app/products': typeof AppProductsIndexRoute
  '/app/purchases': typeof AppPurchasesIndexRoute
  '/app/reports': typeof AppReportsIndexRoute
  '/app/sales': typeof AppSalesIndexRoute
  '/admin/invoices/en/$subscriptionId': typeof AdminInvoicesEnSubscriptionIdRoute
  '/admin/receipts/en/$paymentId': typeof AdminReceiptsEnPaymentIdRoute
  '/api/public/bkash/callback': typeof ApiPublicBkashCallbackRoute
  '/api/public/bkash/webhook': typeof ApiPublicBkashWebhookRoute
  '/api/public/cron/expiry-check': typeof ApiPublicCronExpiryCheckRoute
  '/api/public/cron/invoice-reminders': typeof ApiPublicCronInvoiceRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/impersonate': typeof ImpersonateRoute
  '/login': typeof LoginRoute
  '/renew': typeof RenewRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/demo-requests': typeof AdminDemoRequestsRoute
  '/admin/impersonation-logs': typeof AdminImpersonationLogsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/shops': typeof AdminShopsRouteWithChildren
  '/admin/sms-logs': typeof AdminSmsLogsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/change-password': typeof AppChangePasswordRoute
  '/app/customers': typeof AppCustomersRouteWithChildren
  '/app/installments': typeof AppInstallmentsRoute
  '/app/pay-invoice': typeof AppPayInvoiceRoute
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/shifts': typeof AppShiftsRoute
  '/app/stock': typeof AppStockRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/units': typeof AppUnitsRoute
  '/app/usage': typeof AppUsageRoute
  '/i/$token': typeof ITokenRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/receipts/$paymentId': typeof AdminReceiptsPaymentIdRoute
  '/admin/shops/$shopId': typeof AdminShopsShopIdRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/products/$productId': typeof AppProductsProductIdRoute
  '/app/purchases/new': typeof AppPurchasesNewRoute
  '/app/reports/bkash-book': typeof AppReportsBkashBookRoute
  '/app/reports/cash-book': typeof AppReportsCashBookRoute
  '/app/reports/category-sales': typeof AppReportsCategorySalesRoute
  '/app/reports/customer-sales': typeof AppReportsCustomerSalesRoute
  '/app/reports/discount': typeof AppReportsDiscountRoute
  '/app/reports/installment': typeof AppReportsInstallmentRoute
  '/app/reports/low-stock': typeof AppReportsLowStockRoute
  '/app/reports/payable': typeof AppReportsPayableRoute
  '/app/reports/payment-method': typeof AppReportsPaymentMethodRoute
  '/app/reports/product-sales': typeof AppReportsProductSalesRoute
  '/app/reports/profit': typeof AppReportsProfitRoute
  '/app/reports/purchase': typeof AppReportsPurchaseRoute
  '/app/reports/receivable': typeof AppReportsReceivableRoute
  '/app/reports/sales': typeof AppReportsSalesRoute
  '/app/reports/sales-return': typeof AppReportsSalesReturnRoute
  '/app/reports/shift': typeof AppReportsShiftRoute
  '/app/reports/stock': typeof AppReportsStockRoute
  '/app/reports/stock-movement': typeof AppReportsStockMovementRoute
  '/app/reports/supplier-purchase': typeof AppReportsSupplierPurchaseRoute
  '/app/reports/tax': typeof AppReportsTaxRoute
  '/app/sales/$saleId': typeof AppSalesSaleIdRoute
  '/app/sales/new': typeof AppSalesNewRoute
  '/app/settings/invoice-template': typeof AppSettingsInvoiceTemplateRoute
  '/admin/shops/': typeof AdminShopsIndexRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/products/': typeof AppProductsIndexRoute
  '/app/purchases/': typeof AppPurchasesIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/app/sales/': typeof AppSalesIndexRoute
  '/admin/invoices/en/$subscriptionId': typeof AdminInvoicesEnSubscriptionIdRoute
  '/admin/receipts/en/$paymentId': typeof AdminReceiptsEnPaymentIdRoute
  '/api/public/bkash/callback': typeof ApiPublicBkashCallbackRoute
  '/api/public/bkash/webhook': typeof ApiPublicBkashWebhookRoute
  '/api/public/cron/expiry-check': typeof ApiPublicCronExpiryCheckRoute
  '/api/public/cron/invoice-reminders': typeof ApiPublicCronInvoiceRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/impersonate'
    | '/login'
    | '/renew'
    | '/admin/admins'
    | '/admin/audit-logs'
    | '/admin/demo-requests'
    | '/admin/impersonation-logs'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/shops'
    | '/admin/sms-logs'
    | '/admin/subscriptions'
    | '/app/categories'
    | '/app/change-password'
    | '/app/customers'
    | '/app/installments'
    | '/app/pay-invoice'
    | '/app/reports'
    | '/app/shifts'
    | '/app/stock'
    | '/app/subscription'
    | '/app/suppliers'
    | '/app/units'
    | '/app/usage'
    | '/i/$token'
    | '/admin/'
    | '/app/'
    | '/admin/receipts/$paymentId'
    | '/admin/shops/$shopId'
    | '/app/customers/$customerId'
    | '/app/products/$productId'
    | '/app/purchases/new'
    | '/app/reports/bkash-book'
    | '/app/reports/cash-book'
    | '/app/reports/category-sales'
    | '/app/reports/customer-sales'
    | '/app/reports/discount'
    | '/app/reports/installment'
    | '/app/reports/low-stock'
    | '/app/reports/payable'
    | '/app/reports/payment-method'
    | '/app/reports/product-sales'
    | '/app/reports/profit'
    | '/app/reports/purchase'
    | '/app/reports/receivable'
    | '/app/reports/sales'
    | '/app/reports/sales-return'
    | '/app/reports/shift'
    | '/app/reports/stock'
    | '/app/reports/stock-movement'
    | '/app/reports/supplier-purchase'
    | '/app/reports/tax'
    | '/app/sales/$saleId'
    | '/app/sales/new'
    | '/app/settings/invoice-template'
    | '/admin/shops/'
    | '/app/customers/'
    | '/app/products/'
    | '/app/purchases/'
    | '/app/reports/'
    | '/app/sales/'
    | '/admin/invoices/en/$subscriptionId'
    | '/admin/receipts/en/$paymentId'
    | '/api/public/bkash/callback'
    | '/api/public/bkash/webhook'
    | '/api/public/cron/expiry-check'
    | '/api/public/cron/invoice-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/impersonate'
    | '/login'
    | '/renew'
    | '/admin/admins'
    | '/admin/audit-logs'
    | '/admin/demo-requests'
    | '/admin/impersonation-logs'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/sms-logs'
    | '/admin/subscriptions'
    | '/app/categories'
    | '/app/change-password'
    | '/app/installments'
    | '/app/pay-invoice'
    | '/app/shifts'
    | '/app/stock'
    | '/app/subscription'
    | '/app/suppliers'
    | '/app/units'
    | '/app/usage'
    | '/i/$token'
    | '/admin'
    | '/app'
    | '/admin/receipts/$paymentId'
    | '/admin/shops/$shopId'
    | '/app/customers/$customerId'
    | '/app/products/$productId'
    | '/app/purchases/new'
    | '/app/reports/bkash-book'
    | '/app/reports/cash-book'
    | '/app/reports/category-sales'
    | '/app/reports/customer-sales'
    | '/app/reports/discount'
    | '/app/reports/installment'
    | '/app/reports/low-stock'
    | '/app/reports/payable'
    | '/app/reports/payment-method'
    | '/app/reports/product-sales'
    | '/app/reports/profit'
    | '/app/reports/purchase'
    | '/app/reports/receivable'
    | '/app/reports/sales'
    | '/app/reports/sales-return'
    | '/app/reports/shift'
    | '/app/reports/stock'
    | '/app/reports/stock-movement'
    | '/app/reports/supplier-purchase'
    | '/app/reports/tax'
    | '/app/sales/$saleId'
    | '/app/sales/new'
    | '/app/settings/invoice-template'
    | '/admin/shops'
    | '/app/customers'
    | '/app/products'
    | '/app/purchases'
    | '/app/reports'
    | '/app/sales'
    | '/admin/invoices/en/$subscriptionId'
    | '/admin/receipts/en/$paymentId'
    | '/api/public/bkash/callback'
    | '/api/public/bkash/webhook'
    | '/api/public/cron/expiry-check'
    | '/api/public/cron/invoice-reminders'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/impersonate'
    | '/login'
    | '/renew'
    | '/admin/admins'
    | '/admin/audit-logs'
    | '/admin/demo-requests'
    | '/admin/impersonation-logs'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/shops'
    | '/admin/sms-logs'
    | '/admin/subscriptions'
    | '/app/categories'
    | '/app/change-password'
    | '/app/customers'
    | '/app/installments'
    | '/app/pay-invoice'
    | '/app/reports'
    | '/app/shifts'
    | '/app/stock'
    | '/app/subscription'
    | '/app/suppliers'
    | '/app/units'
    | '/app/usage'
    | '/i/$token'
    | '/admin/'
    | '/app/'
    | '/admin/receipts/$paymentId'
    | '/admin/shops/$shopId'
    | '/app/customers/$customerId'
    | '/app/products/$productId'
    | '/app/purchases/new'
    | '/app/reports/bkash-book'
    | '/app/reports/cash-book'
    | '/app/reports/category-sales'
    | '/app/reports/customer-sales'
    | '/app/reports/discount'
    | '/app/reports/installment'
    | '/app/reports/low-stock'
    | '/app/reports/payable'
    | '/app/reports/payment-method'
    | '/app/reports/product-sales'
    | '/app/reports/profit'
    | '/app/reports/purchase'
    | '/app/reports/receivable'
    | '/app/reports/sales'
    | '/app/reports/sales-return'
    | '/app/reports/shift'
    | '/app/reports/stock'
    | '/app/reports/stock-movement'
    | '/app/reports/supplier-purchase'
    | '/app/reports/tax'
    | '/app/sales/$saleId'
    | '/app/sales/new'
    | '/app/settings/invoice-template'
    | '/admin/shops/'
    | '/app/customers/'
    | '/app/products/'
    | '/app/purchases/'
    | '/app/reports/'
    | '/app/sales/'
    | '/admin/invoices/en/$subscriptionId'
    | '/admin/receipts/en/$paymentId'
    | '/api/public/bkash/callback'
    | '/api/public/bkash/webhook'
    | '/api/public/cron/expiry-check'
    | '/api/public/cron/invoice-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ImpersonateRoute: typeof ImpersonateRoute
  LoginRoute: typeof LoginRoute
  RenewRoute: typeof RenewRoute
  ITokenRoute: typeof ITokenRoute
  ApiPublicBkashCallbackRoute: typeof ApiPublicBkashCallbackRoute
  ApiPublicBkashWebhookRoute: typeof ApiPublicBkashWebhookRoute
  ApiPublicCronExpiryCheckRoute: typeof ApiPublicCronExpiryCheckRoute
  ApiPublicCronInvoiceRemindersRoute: typeof ApiPublicCronInvoiceRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/renew': {
      id: '/renew'
      path: '/renew'
      fullPath: '/renew'
      preLoaderRoute: typeof RenewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impersonate': {
      id: '/impersonate'
      path: '/impersonate'
      fullPath: '/impersonate'
      preLoaderRoute: typeof ImpersonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/i/$token': {
      id: '/i/$token'
      path: '/i/$token'
      fullPath: '/i/$token'
      preLoaderRoute: typeof ITokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/usage': {
      id: '/app/usage'
      path: '/usage'
      fullPath: '/app/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/units': {
      id: '/app/units'
      path: '/units'
      fullPath: '/app/units'
      preLoaderRoute: typeof AppUnitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscription': {
      id: '/app/subscription'
      path: '/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stock': {
      id: '/app/stock'
      path: '/stock'
      fullPath: '/app/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shifts': {
      id: '/app/shifts'
      path: '/shifts'
      fullPath: '/app/shifts'
      preLoaderRoute: typeof AppShiftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pay-invoice': {
      id: '/app/pay-invoice'
      path: '/pay-invoice'
      fullPath: '/app/pay-invoice'
      preLoaderRoute: typeof AppPayInvoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/installments': {
      id: '/app/installments'
      path: '/installments'
      fullPath: '/app/installments'
      preLoaderRoute: typeof AppInstallmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/change-password': {
      id: '/app/change-password'
      path: '/change-password'
      fullPath: '/app/change-password'
      preLoaderRoute: typeof AppChangePasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categories': {
      id: '/app/categories'
      path: '/categories'
      fullPath: '/app/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sms-logs': {
      id: '/admin/sms-logs'
      path: '/sms-logs'
      fullPath: '/admin/sms-logs'
      preLoaderRoute: typeof AdminSmsLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shops': {
      id: '/admin/shops'
      path: '/shops'
      fullPath: '/admin/shops'
      preLoaderRoute: typeof AdminShopsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/impersonation-logs': {
      id: '/admin/impersonation-logs'
      path: '/impersonation-logs'
      fullPath: '/admin/impersonation-logs'
      preLoaderRoute: typeof AdminImpersonationLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/demo-requests': {
      id: '/admin/demo-requests'
      path: '/demo-requests'
      fullPath: '/admin/demo-requests'
      preLoaderRoute: typeof AdminDemoRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/sales/': {
      id: '/app/sales/'
      path: '/sales'
      fullPath: '/app/sales/'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/': {
      id: '/app/reports/'
      path: '/'
      fullPath: '/app/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/purchases/': {
      id: '/app/purchases/'
      path: '/purchases'
      fullPath: '/app/purchases/'
      preLoaderRoute: typeof AppPurchasesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products/': {
      id: '/app/products/'
      path: '/products'
      fullPath: '/app/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers/': {
      id: '/app/customers/'
      path: '/'
      fullPath: '/app/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppCustomersRoute
    }
    '/admin/shops/': {
      id: '/admin/shops/'
      path: '/'
      fullPath: '/admin/shops/'
      preLoaderRoute: typeof AdminShopsIndexRouteImport
      parentRoute: typeof AdminShopsRoute
    }
    '/app/settings/invoice-template': {
      id: '/app/settings/invoice-template'
      path: '/settings/invoice-template'
      fullPath: '/app/settings/invoice-template'
      preLoaderRoute: typeof AppSettingsInvoiceTemplateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales/new': {
      id: '/app/sales/new'
      path: '/sales/new'
      fullPath: '/app/sales/new'
      preLoaderRoute: typeof AppSalesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales/$saleId': {
      id: '/app/sales/$saleId'
      path: '/sales/$saleId'
      fullPath: '/app/sales/$saleId'
      preLoaderRoute: typeof AppSalesSaleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/tax': {
      id: '/app/reports/tax'
      path: '/tax'
      fullPath: '/app/reports/tax'
      preLoaderRoute: typeof AppReportsTaxRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/supplier-purchase': {
      id: '/app/reports/supplier-purchase'
      path: '/supplier-purchase'
      fullPath: '/app/reports/supplier-purchase'
      preLoaderRoute: typeof AppReportsSupplierPurchaseRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/stock-movement': {
      id: '/app/reports/stock-movement'
      path: '/stock-movement'
      fullPath: '/app/reports/stock-movement'
      preLoaderRoute: typeof AppReportsStockMovementRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/stock': {
      id: '/app/reports/stock'
      path: '/stock'
      fullPath: '/app/reports/stock'
      preLoaderRoute: typeof AppReportsStockRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/shift': {
      id: '/app/reports/shift'
      path: '/shift'
      fullPath: '/app/reports/shift'
      preLoaderRoute: typeof AppReportsShiftRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/sales-return': {
      id: '/app/reports/sales-return'
      path: '/sales-return'
      fullPath: '/app/reports/sales-return'
      preLoaderRoute: typeof AppReportsSalesReturnRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/sales': {
      id: '/app/reports/sales'
      path: '/sales'
      fullPath: '/app/reports/sales'
      preLoaderRoute: typeof AppReportsSalesRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/receivable': {
      id: '/app/reports/receivable'
      path: '/receivable'
      fullPath: '/app/reports/receivable'
      preLoaderRoute: typeof AppReportsReceivableRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/purchase': {
      id: '/app/reports/purchase'
      path: '/purchase'
      fullPath: '/app/reports/purchase'
      preLoaderRoute: typeof AppReportsPurchaseRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/profit': {
      id: '/app/reports/profit'
      path: '/profit'
      fullPath: '/app/reports/profit'
      preLoaderRoute: typeof AppReportsProfitRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/product-sales': {
      id: '/app/reports/product-sales'
      path: '/product-sales'
      fullPath: '/app/reports/product-sales'
      preLoaderRoute: typeof AppReportsProductSalesRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/payment-method': {
      id: '/app/reports/payment-method'
      path: '/payment-method'
      fullPath: '/app/reports/payment-method'
      preLoaderRoute: typeof AppReportsPaymentMethodRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/payable': {
      id: '/app/reports/payable'
      path: '/payable'
      fullPath: '/app/reports/payable'
      preLoaderRoute: typeof AppReportsPayableRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/low-stock': {
      id: '/app/reports/low-stock'
      path: '/low-stock'
      fullPath: '/app/reports/low-stock'
      preLoaderRoute: typeof AppReportsLowStockRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/installment': {
      id: '/app/reports/installment'
      path: '/installment'
      fullPath: '/app/reports/installment'
      preLoaderRoute: typeof AppReportsInstallmentRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/discount': {
      id: '/app/reports/discount'
      path: '/discount'
      fullPath: '/app/reports/discount'
      preLoaderRoute: typeof AppReportsDiscountRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/customer-sales': {
      id: '/app/reports/customer-sales'
      path: '/customer-sales'
      fullPath: '/app/reports/customer-sales'
      preLoaderRoute: typeof AppReportsCustomerSalesRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/category-sales': {
      id: '/app/reports/category-sales'
      path: '/category-sales'
      fullPath: '/app/reports/category-sales'
      preLoaderRoute: typeof AppReportsCategorySalesRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/cash-book': {
      id: '/app/reports/cash-book'
      path: '/cash-book'
      fullPath: '/app/reports/cash-book'
      preLoaderRoute: typeof AppReportsCashBookRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/bkash-book': {
      id: '/app/reports/bkash-book'
      path: '/bkash-book'
      fullPath: '/app/reports/bkash-book'
      preLoaderRoute: typeof AppReportsBkashBookRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/purchases/new': {
      id: '/app/purchases/new'
      path: '/purchases/new'
      fullPath: '/app/purchases/new'
      preLoaderRoute: typeof AppPurchasesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products/$productId': {
      id: '/app/products/$productId'
      path: '/products/$productId'
      fullPath: '/app/products/$productId'
      preLoaderRoute: typeof AppProductsProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers/$customerId': {
      id: '/app/customers/$customerId'
      path: '/$customerId'
      fullPath: '/app/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppCustomersRoute
    }
    '/admin/shops/$shopId': {
      id: '/admin/shops/$shopId'
      path: '/$shopId'
      fullPath: '/admin/shops/$shopId'
      preLoaderRoute: typeof AdminShopsShopIdRouteImport
      parentRoute: typeof AdminShopsRoute
    }
    '/admin/receipts/$paymentId': {
      id: '/admin/receipts/$paymentId'
      path: '/receipts/$paymentId'
      fullPath: '/admin/receipts/$paymentId'
      preLoaderRoute: typeof AdminReceiptsPaymentIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/cron/invoice-reminders': {
      id: '/api/public/cron/invoice-reminders'
      path: '/api/public/cron/invoice-reminders'
      fullPath: '/api/public/cron/invoice-reminders'
      preLoaderRoute: typeof ApiPublicCronInvoiceRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/expiry-check': {
      id: '/api/public/cron/expiry-check'
      path: '/api/public/cron/expiry-check'
      fullPath: '/api/public/cron/expiry-check'
      preLoaderRoute: typeof ApiPublicCronExpiryCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bkash/webhook': {
      id: '/api/public/bkash/webhook'
      path: '/api/public/bkash/webhook'
      fullPath: '/api/public/bkash/webhook'
      preLoaderRoute: typeof ApiPublicBkashWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bkash/callback': {
      id: '/api/public/bkash/callback'
      path: '/api/public/bkash/callback'
      fullPath: '/api/public/bkash/callback'
      preLoaderRoute: typeof ApiPublicBkashCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/receipts/en/$paymentId': {
      id: '/admin/receipts/en/$paymentId'
      path: '/receipts/en/$paymentId'
      fullPath: '/admin/receipts/en/$paymentId'
      preLoaderRoute: typeof AdminReceiptsEnPaymentIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices/en/$subscriptionId': {
      id: '/admin/invoices/en/$subscriptionId'
      path: '/invoices/en/$subscriptionId'
      fullPath: '/admin/invoices/en/$subscriptionId'
      preLoaderRoute: typeof AdminInvoicesEnSubscriptionIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminShopsRouteChildren {
  AdminShopsShopIdRoute: typeof AdminShopsShopIdRoute
  AdminShopsIndexRoute: typeof AdminShopsIndexRoute
}

const AdminShopsRouteChildren: AdminShopsRouteChildren = {
  AdminShopsShopIdRoute: AdminShopsShopIdRoute,
  AdminShopsIndexRoute: AdminShopsIndexRoute,
}

const AdminShopsRouteWithChildren = AdminShopsRoute._addFileChildren(
  AdminShopsRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminDemoRequestsRoute: typeof AdminDemoRequestsRoute
  AdminImpersonationLogsRoute: typeof AdminImpersonationLogsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AdminShopsRoute: typeof AdminShopsRouteWithChildren
  AdminSmsLogsRoute: typeof AdminSmsLogsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminReceiptsPaymentIdRoute: typeof AdminReceiptsPaymentIdRoute
  AdminInvoicesEnSubscriptionIdRoute: typeof AdminInvoicesEnSubscriptionIdRoute
  AdminReceiptsEnPaymentIdRoute: typeof AdminReceiptsEnPaymentIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminDemoRequestsRoute: AdminDemoRequestsRoute,
  AdminImpersonationLogsRoute: AdminImpersonationLogsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSetupRoute: AdminSetupRoute,
  AdminShopsRoute: AdminShopsRouteWithChildren,
  AdminSmsLogsRoute: AdminSmsLogsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminReceiptsPaymentIdRoute: AdminReceiptsPaymentIdRoute,
  AdminInvoicesEnSubscriptionIdRoute: AdminInvoicesEnSubscriptionIdRoute,
  AdminReceiptsEnPaymentIdRoute: AdminReceiptsEnPaymentIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppCustomersRouteChildren {
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
}

const AppCustomersRouteChildren: AppCustomersRouteChildren = {
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
}

const AppCustomersRouteWithChildren = AppCustomersRoute._addFileChildren(
  AppCustomersRouteChildren,
)

interface AppReportsRouteChildren {
  AppReportsBkashBookRoute: typeof AppReportsBkashBookRoute
  AppReportsCashBookRoute: typeof AppReportsCashBookRoute
  AppReportsCategorySalesRoute: typeof AppReportsCategorySalesRoute
  AppReportsCustomerSalesRoute: typeof AppReportsCustomerSalesRoute
  AppReportsDiscountRoute: typeof AppReportsDiscountRoute
  AppReportsInstallmentRoute: typeof AppReportsInstallmentRoute
  AppReportsLowStockRoute: typeof AppReportsLowStockRoute
  AppReportsPayableRoute: typeof AppReportsPayableRoute
  AppReportsPaymentMethodRoute: typeof AppReportsPaymentMethodRoute
  AppReportsProductSalesRoute: typeof AppReportsProductSalesRoute
  AppReportsProfitRoute: typeof AppReportsProfitRoute
  AppReportsPurchaseRoute: typeof AppReportsPurchaseRoute
  AppReportsReceivableRoute: typeof AppReportsReceivableRoute
  AppReportsSalesRoute: typeof AppReportsSalesRoute
  AppReportsSalesReturnRoute: typeof AppReportsSalesReturnRoute
  AppReportsShiftRoute: typeof AppReportsShiftRoute
  AppReportsStockRoute: typeof AppReportsStockRoute
  AppReportsStockMovementRoute: typeof AppReportsStockMovementRoute
  AppReportsSupplierPurchaseRoute: typeof AppReportsSupplierPurchaseRoute
  AppReportsTaxRoute: typeof AppReportsTaxRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsBkashBookRoute: AppReportsBkashBookRoute,
  AppReportsCashBookRoute: AppReportsCashBookRoute,
  AppReportsCategorySalesRoute: AppReportsCategorySalesRoute,
  AppReportsCustomerSalesRoute: AppReportsCustomerSalesRoute,
  AppReportsDiscountRoute: AppReportsDiscountRoute,
  AppReportsInstallmentRoute: AppReportsInstallmentRoute,
  AppReportsLowStockRoute: AppReportsLowStockRoute,
  AppReportsPayableRoute: AppReportsPayableRoute,
  AppReportsPaymentMethodRoute: AppReportsPaymentMethodRoute,
  AppReportsProductSalesRoute: AppReportsProductSalesRoute,
  AppReportsProfitRoute: AppReportsProfitRoute,
  AppReportsPurchaseRoute: AppReportsPurchaseRoute,
  AppReportsReceivableRoute: AppReportsReceivableRoute,
  AppReportsSalesRoute: AppReportsSalesRoute,
  AppReportsSalesReturnRoute: AppReportsSalesReturnRoute,
  AppReportsShiftRoute: AppReportsShiftRoute,
  AppReportsStockRoute: AppReportsStockRoute,
  AppReportsStockMovementRoute: AppReportsStockMovementRoute,
  AppReportsSupplierPurchaseRoute: AppReportsSupplierPurchaseRoute,
  AppReportsTaxRoute: AppReportsTaxRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppRouteChildren {
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppChangePasswordRoute: typeof AppChangePasswordRoute
  AppCustomersRoute: typeof AppCustomersRouteWithChildren
  AppInstallmentsRoute: typeof AppInstallmentsRoute
  AppPayInvoiceRoute: typeof AppPayInvoiceRoute
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppShiftsRoute: typeof AppShiftsRoute
  AppStockRoute: typeof AppStockRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppUnitsRoute: typeof AppUnitsRoute
  AppUsageRoute: typeof AppUsageRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProductsProductIdRoute: typeof AppProductsProductIdRoute
  AppPurchasesNewRoute: typeof AppPurchasesNewRoute
  AppSalesSaleIdRoute: typeof AppSalesSaleIdRoute
  AppSalesNewRoute: typeof AppSalesNewRoute
  AppSettingsInvoiceTemplateRoute: typeof AppSettingsInvoiceTemplateRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppPurchasesIndexRoute: typeof AppPurchasesIndexRoute
  AppSalesIndexRoute: typeof AppSalesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriesRoute: AppCategoriesRoute,
  AppChangePasswordRoute: AppChangePasswordRoute,
  AppCustomersRoute: AppCustomersRouteWithChildren,
  AppInstallmentsRoute: AppInstallmentsRoute,
  AppPayInvoiceRoute: AppPayInvoiceRoute,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppShiftsRoute: AppShiftsRoute,
  AppStockRoute: AppStockRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppUnitsRoute: AppUnitsRoute,
  AppUsageRoute: AppUsageRoute,
  AppIndexRoute: AppIndexRoute,
  AppProductsProductIdRoute: AppProductsProductIdRoute,
  AppPurchasesNewRoute: AppPurchasesNewRoute,
  AppSalesSaleIdRoute: AppSalesSaleIdRoute,
  AppSalesNewRoute: AppSalesNewRoute,
  AppSettingsInvoiceTemplateRoute: AppSettingsInvoiceTemplateRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppPurchasesIndexRoute: AppPurchasesIndexRoute,
  AppSalesIndexRoute: AppSalesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ImpersonateRoute: ImpersonateRoute,
  LoginRoute: LoginRoute,
  RenewRoute: RenewRoute,
  ITokenRoute: ITokenRoute,
  ApiPublicBkashCallbackRoute: ApiPublicBkashCallbackRoute,
  ApiPublicBkashWebhookRoute: ApiPublicBkashWebhookRoute,
  ApiPublicCronExpiryCheckRoute: ApiPublicCronExpiryCheckRoute,
  ApiPublicCronInvoiceRemindersRoute: ApiPublicCronInvoiceRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
